-- SQL Script to Create Teacher Accounts in Supabase
-- Run this in your Supabase SQL Editor

-- Create teacher accounts directly in auth.users table
INSERT INTO auth.users (
  id,
  instance_id,
  aud,
  role,
  email,
  encrypted_password,
  email_confirmed_at,
  invited_at,
  confirmation_sent_at,
  recovery_sent_at,
  email_change_sent_at,
  last_sign_in_at,
  raw_app_meta_data,
  raw_user_meta_data,
  is_super_admin,
  created_at,
  updated_at,
  phone,
  phone_confirmed_at,
  phone_change,
  phone_change_token,
  phone_change_sent_at,
  confirmed_at,
  email_change_token_current,
  email_change_confirm_status,
  banned_until,
  reauthentication_token,
  reauthentication_sent_at,
  is_sso_user,
  deleted_at
) VALUES 
-- Teacher 1: Shiv Prakash Yadav (sp8@photon)
(
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000000',
  'authenticated',
  'authenticated',
  'sp8@photon',
  crypt('sp8@photon', gen_salt('bf')),
  now(),
  now(),
  now(),
  null,
  null,
  null,
  '{"provider": "email", "providers": ["email"]}',
  '{"name": "Shiv Prakash Yadav", "role": "teacher"}',
  false,
  now(),
  now(),
  null,
  null,
  '',
  '',
  null,
  now(),
  '',
  0,
  null,
  '',
  null,
  false,
  null
),
-- Teacher 2: Mahavir Kesari (mk6@photon)
(
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000000',
  'authenticated',
  'authenticated',
  'mk6@photon',
  crypt('mk6@photon', gen_salt('bf')),
  now(),
  now(),
  now(),
  null,
  null,
  null,
  '{"provider": "email", "providers": ["email"]}',
  '{"name": "Mahavir Kesari", "role": "teacher"}',
  false,
  now(),
  now(),
  null,
  null,
  '',
  '',
  null,
  now(),
  '',
  0,
  null,
  '',
  null,
  false,
  null
),
-- Teacher 3: AK Mishra (ak5@photon)
(
  gen_random_uuid(),
  '00000000-0000-0000-0000-000000000000',
  'authenticated',
  'authenticated',
  'ak5@photon',
  crypt('ak5@photon', gen_salt('bf')),
  now(),
  now(),
  now(),
  null,
  null,
  null,
  '{"provider": "email", "providers": ["email"]}',
  '{"name": "AK Mishra", "role": "teacher"}',
  false,
  now(),
  now(),
  null,
  null,
  '',
  '',
  null,
  now(),
  '',
  0,
  null,
  '',
  null,
  false,
  null
)
ON CONFLICT (email) DO NOTHING;

-- Verify the users were created
SELECT email, raw_user_meta_data->>'name' as name, created_at 
FROM auth.users 
WHERE email IN ('sp8@photon', 'mk6@photon', 'ak5@photon');
